### ISSUE TITLE
HopGlass Features

### ISSUE THREAD

**Issue by plumpudding** [ffrgb/meshviewer#117]
This is a accumulative issue on all hopglass features:

Do you think it would be possible to integrate these features into ffrgb/meshviewer:

- Bidirectional TQ (kinda in the client, just no data supplied)
- Router pics
- GW statistics (by clients, by nodes)
- Distinguish cable links from wifi links
- Distinguish L2TP links from fastd links
- resolve and display nexthops
- gateway count in the mesh stats

also these: https://github.com/FreifunkBremen/meshviewer-ffrgb/commit/1a949df12676a388eb5af42773bebf43a2366340

- display full airtime data
- 5GHz vs 2.4 GHz vs LAN clients
- display all memory info

This will probably break compatibility with meshviewer nodes.json v2, but this is connected to https://github.com/FreifunkBremen/yanic/issues/50

Probably we three (@genofire, @xf- and me) should get mumble at some point

The idea behind this is that I see this repository as upstream for hopglass and I want to try once more to get these features into upstream because it is unnecessary to maintain another fork.

**Comment by xf-** [comment]
Bidirectional TQ (kinda in the client, just no data supplied)
->  don't understand, never seen

    Router pics
-> nogo

    GW statistics (by clients, by nodes)
-> don't understand, never seen

    Distinguish cable links from wifi links
    Distinguish L2TP links from fastd links
-> #69

    resolve and display nexthops
-> #35 

also these: hopglass/hopglass@5cb88e8

    display full airtime data
    5GHz vs 2.4 GHz vs LAN clients
-> Planed at some point

    display all memory info
-> You mean more hardware stats?

**Comment by plumpudding** [comment]
Bidirectional TQ: Look at https://lln.map.ffgl.eu/#!v:g, for each link there are two TQs; one for each direction. In Hopglass this was implemented in the graph by drawing each link once for each direction with a little gap in between.

**Comment by xf-** [comment]
The implementation is not so nice, a lot of parts are missing: Map, hover on map, infobox/link. Also i find the doubled entries in infobox/node confusion. (Only way to see numbers and not only colors.) Connections are also only TQ and not sortable for worst connection.

What is the advantage?
TQ is last minute and can change often. A graph would be more interesting.

**Comment by plumpudding** [comment]
As I said I am not happy with the implementation in the infobox either, so maybe we can work out a better way like two columns for the TQ in both directions.

**Comment by plumpudding** [comment]
> Router pics
> -> nogo

I don't want this to turn into a discussion but I just want to know: Do you not want router pics because of aesthetical reasons or because it's a hard-to-maintain implementation or something in that direction?
Many people including me like the router pics and implementing them with an opt-in option would be an advantage for everyone IMO.

**Comment by xf-** [comment]
Bidirectional TQ: I don't know, i want a understandable utility without a manual. Like a wrote, a grafana image with both values over last Day would be much better. A lot of numbers and columns for a property that changes every minute.

GW statistics (by clients, by nodes): Can think about it, but stats stuff get more heavy. Personally i like idea of filtering nodes per gateway. But clients it is the same filter twice with another value. This is more statistics - grafana.

2.4 Ghz, 5Ghz and LAN is more or less planned. Bremen already has it visible, but i don't like it (not intuitive and i don't want to explain colors on map). Wifi/VPN stuff only if we have enough info, because this costs performance.

About images:
- Implementation (GUI) looks not so nice
- No advantage
- Bad for mobile, you need to scroll a image and less space for the name (we use more space for the map, because with buttons you need space to navigate the map)
- Maintaining images
- 90% same image for 841/842, 1043 NS2/5 (loco), UnifiAP
- I don't like optional code in a fronted application
  - Maintenance
  - More code
  - Needs to be tested
  - New issues for not available router images

**Comment by plumpudding** [comment]
> Bidirectional TQ: I don't know, i want a understandable utility without a manual. Like a wrote, a grafana image with both values over last Day would be much better. A lot of numbers and columns for a property that changes every minute.

We can agree on this: The table should stay as small as possible. In that case it should be well-defined what value is displayed there: Is it the average of both directions or the lower one?

> GW statistics (by clients, by nodes): Can think about it, but stats stuff get more heavy. Personally i like idea of filtering nodes per gateway. But clients it is the same filter twice with another value. This is more statistics - grafana.

GW by nodes is enough, but there will be technical challenges like resolving the mac address to show the actual name of the gateway. 

In HopGlass we just give the user the option to configure an external source for hardware pictures. If it isn't configured, everything will be the same as it was before the commit. The hardware pictures are maintained in a seperate repository: https://github.com/moorviper/meshviewer_hwpics
There are alternative ways to place the router pic so that it doesn't take up any extra space: 
https://github.com/hopglass/hopglass/issues/75
https://github.com/rhigma/ff-router-mockup/blob/images/ff-router-mockup-1043-small-right.png
Optional code is the only argument you can make. I just don't want to have to create another fork again to add router pics. I can't remove them from all the eulenfunk maps either, as they are already a feature. Of course this should not be a reason to add this feature to this repository, but I'm trying to explain my view on that feature.

**Comment by xf-** [comment]
> We can agree on this: The table should stay as small as possible. In that case it should be well-defined what value is displayed there: Is it the average of both directions or the lower one?
Like i wrote, its a detailed feature. I would use grafana for this one. In general a mix would be nice and if one site is 0 = offline. I think our backends behave differently. If we have a nice option to improve it, i'm open for it, but 1 value should be enough.

> GW by nodes is enough, but there will be technical challenges like resolving the mac address to show the actual name of the gateway.
More or less easy. respondd runs on server as well and is a node. I like this, because a gateway is only a flag.

**Comment by plumpudding** [comment]
So you think only one value should be transmitted per link?

**Comment by xf-** [comment]
We can have 2 values (show only one), but for example the link list. How to decide which one or use the average?

**Comment by rotanid** [comment]
oh, thanks for pointing out that bidirectional TQ is also missing in this "fork".
that's a very helpful feature for debugging...

**Comment by plumpudding** [comment]
@rotanid bidirectional tq in hopglass is mostly done by simply sending each link's info twice.

**Comment by xf-** [comment]
Drawn twice no good idea.

I will close this issue. Please create a single issue per feature. This way it is easier to discuss them.
