### ISSUE TITLE
Please add information about the work progress

### ISSUE THREAD

**Issue by rubo77** [ffrgb/meshviewer#188]
I try to merge this project back into the original project: https://github.com/ffnord/meshviewer

It is not clear, how you work in this project. Please add informations to the README:

- How are the different branches used
- how do you prepare releases
- mark stable commits as tags with versions

please use the original tags from https://github.com/ffnord/meshviewer/tags appended with "-ffrgb", so the next stable version should be tagged as v5-ffrgb.

The other main branch will also be added to the original project, see https://github.com/hopglass/hopglass/issues/98

**Comment by xf-** [comment]
We discussed this in IRC. Merging/fast forward on ffnord with no development is only confusing, because bug reports are in wrong repo. We also use another Backend and in future not compatible to old nodes v1/v2.
Information about changes can be found in gitbooks and primarily in CHANGELOG (linked in README).
