### ISSUE TITLE
Allow overlaying a GeoJSON file on map

### ISSUE THREAD

**Issue by oliver** [ffrgb/meshviewer#259]
## Is your feature request related to a problem? Please describe.

For Freifunk installations at temporary events I want to see on the map the locations of tents and other event stuff, to determine eg. the tent in which a node is located.

## Describe the solution you'd like

I want to display a GeoJSON file overlaid on the Openstreetmap tiles, to display the locations of tents and other event stuff. I already have a GeoJSON file with these tents.

## Describe alternatives you've considered

Current "solution" is to not display the tent locations at all in the Meshviewer. We have an additional tool with a map page anyway which displays the GeoJSON file; but it would be useful to have the tents displayed in Meshviewer as well.

**Comment by xf-** [comment]
sounds interessing - should be easy

**Comment by xf-** [comment]
implemented

**Comment by oliver** [comment]
Wow, thanks a lot, great that you implemented this so quickly!

Would it be possible to load the GeoJSON data from a separate file though? MyGeoJSON file currently has 31 KB, that's quite unwieldy to add to the config file.

**Comment by xf-** [comment]
config.js supports js. you can load it.
Similar to https://github.com/ffrgb/meshviewer/blob/develop/config.default.js#L28-L44 and helper has a json loader. i had some problems with colors, that's why i spliced the config into json and option.
(leaflet had GeoJSON support with few lines)

**Comment by lrnzo** [comment]
at Freifunk Nordwest we are dealing with a set of round 2 dozen "hoods" or "domains" as in recent gluon speek. they are already in our [map](https://map.ffnw.de) as geoJSON object. This is very cool. However we recognized that the nodes and the links are not clickable (while mousepointer is within a domain) right from a freshly loaded meshviewer tab. You have to wait a few seconds (up to a minute or so) until the tooltip for a node inside a hood appears and the node is clickable. Furthermore on [expmap](https://map.ffnw.de/testing) i added
```
onEachFeature: function (feature, layer) {
  var str = (Object.values(feature.properties.name)[0]+"<br>"+ feature.properties.prefix6 +"<br>"+feature.properties.prefix4);
  layer.bindPopup(str);
}
```
with this function too, the nodes and links are not clickable from the start but after some time. I think it has something to do with the meshviewer.json being refreshed, so that the nodes and links get push to the foreground (sorry for not knowing the correct javascript/leaflet nomenclature here). How can it be achieved that the objects/layers (?) from the meshviewer.json are always on top of everything, so that they are always clickable?

**Comment by rubo77** [comment]
You should open a new issue for this

**Comment by lrnzo** [comment]
done.
