### ISSUE TITLE
Apply Filter via URL

### ISSUE THREAD

**Issue by mmalte** [ffrgb/meshviewer#301]
It would be great to apply filters via URL, this would allow us to share links with filters or store them as bookmarks.

It would for example provide the possibility, to share a link with router that still need an update via social media.

It would be most convenient if the URL would change each time you click on a filter in the statistics tab.

**Comment by genofire** [comment]
There was already a issue in the past - but we do not have time to implement it.

**Comment by xf-** [comment]
Currently not possible. Currently the filters are more or less not self aware. That is the reason why it is not possible to implement it in current structure. Only way would be with "click" on the filters after loading all nodes and apply one by one.
I have currently no plan of implementing this, because it needs a rewrite of the whole filters. v12 is more important replacing the module loading. More and more Modules can't be update because the loading isn't compatible.

**Comment by mmalte** [comment]
Thank you for the insights

**Comment by xf-** [comment]
If it would be possible to set current filters and apply them, it would be already implemented into meshviewer.
