### ISSUE TITLE
json node list available?

### ISSUE THREAD

**Issue by boschkundendienst** [ffrgb/meshviewer#335]
Hi, I stumbled upon `https://regensburg.freifunk.net/meshviewer/nodelist.json`  but it seems it is no longer updated/maintained.
Is there currently a version online where I get a .json representation of the ` land.regensburg.freifunk` network?

Thanks in advance

Peter

**Comment by xf-** [comment]
Load the normal meshviewer.json and filter
```
nodes: [ { domain: "ffrgb_uml"} ]
```

**Comment by derpcfreak** [comment]
ok, did that but is there no actual data? I get results like this

```
    "firstseen": "2017-09-21T15:57:45+0200",
    "lastseen": "2020-11-24T14:35:30+0100",
```

which have not been updated since 2020!
Is there no "live" JSON API?

**Comment by maurerle** [comment]
You probably looked at the meshviewer.json at this location https://regensburg.freifunk.net/meshviewer/meshviewer.json
which is just an old relic and not updated since "2020-11-24T18:04:03+0100"

When you go to https://regensburg.freifunk.net/en/network/map/ - press F12 and search the meshviewer.json in the network tab which gets loaded - you see, that the current file can be found here:
https://regensburg.freifunk.net/data/meshviewer.json
which also has a recent `timestamp` field.

**Comment by boschkundendienst** [comment]
Thank you very much, that seems to be the actual data. I am testing tonight.
