### ISSUE TITLE
add nexthop+gateway information

### ISSUE THREAD

**Issue by rotanid** [ffrgb/meshviewer#35]
when looking at nodes that are only meshing, have no direct uplink, it would be nice to know which gateway they use via which nexthop they are meshing with.

as an example, look at this node:
https://map.tecff.de/#!v:m;n:60e327be1d7a

only works with gluon v2016.2.x and very new hopglass+hopglass-server as far as i know, so could be difficult to get working without hopglass-server...

**Comment by xf-** [comment]
We don't use the hopglass-server and have no plans todo so. I want to avoid the overhead for this. You could create a fork and rebase/apply your patchset or maybe use a travis task.

**Comment by genofire** [comment]
maybe it is one for the `respondd` https://github.com/FreifunkBremen/meshviewer-ffrgb/pull/1

**Comment by xf-** [comment]
Is this information direct in json or is it a search?

**Comment by genofire** [comment]
oh, it is legay in alfred :)

```
{
  "statistics": {
    "gateway": "vpnnodeid",
    ...
  },
  ...
}
```

**Comment by xf-** [comment]
Isn't in our file, but it can be found going stepByStep similar to #34 or forcegraph

**Comment by rotanid** [comment]
what exactly is ffrgb using, if not hopglass-server and not respondd-collector?
is it ffmap-backend? if yes, keep in mind that alfred won't be around forever, it's kind of legacy - and ffmap-backend has not maintainer anymore

**Comment by xf-** [comment]
Yes, we use ffmap-backend. If the info is preset in json, it should be easy (next node to Gateway and gateway itself). Maybe add something dynamic like stat images. Last commit was for more generic showBar function.

**Comment by genofire** [comment]
You are correct, it is not the `vpnodeid`. It is just the `nextnodeid`, on this way we have to make it recursive to the vpn or just show the next node. (Hopglass makes boths.)

I prefere all recursive method to make them optional and switch them off by default.

**Comment by SimJoSt** [comment]
> as an example, look at this node:
https://map.tecff.de/#!v:m;n:60e327be1d7a

@rotanid I couldn't find the information you described in the info card of the node to which you provided a link.
I would very much like a feature like this, as it makes the inner workings of the mesh much more transparent.

**Comment by genofire** [comment]
I think, because he is offline - the question is, why the links are still painted.

**Comment by rotanid** [comment]
it's below the ip addresses, above the autoupdater information

**Comment by SimJoSt** [comment]
> I think, because he is offline - the question is, why the links are still painted.
It's online again. Looks pretty neat and helpful.

@rotanid Why is there a ` -> ... -> ` after the node which it connects to the gateway over?
I thought it could mean, that after the node there is another (unknown) node in the chain, but after following the chain, there wasn't.

**Comment by rotanid** [comment]
it may be because it can't be said from the data, if there are other nodes in between.
the data only contains nextnode and gateway, afaik.

**Comment by xf-** [comment]
I think currently yanic only provides the gateway. Gateway could be added, but next hop isn't clear or?

**Comment by genofire** [comment]
okay all information together.
There are two publish values by a gluon node.
```
{
  "statistics": {
    "gateway": "mac address of gateway",
    "gateway6": "mac address of gateway ipv6 - (in development)",
    "gateway_nexthop": "mac address of next hop to gateway",
    ...
  },
  ...
}
```

So we did not need a recursive version to get the values like hopglass `nextHopToGateway -> ... -> gateway`

yanic support since a few hours all values.
In ffmap-backend only "gateway" on some branches :( like `detailed-rrds` https://github.com/ffnord/ffmap-backend/blob/detailed-rrds/lib/nodes.py#L89)

**Comment by plumpudding** [comment]
> So we did not need a recursive version to get the values like hopglass nextHopToGateway -> ... -> gateway

HopGlass only uses the recursive function to display all hops to the gateway ([example](https://bgl.map.ffgl.eu/#!v:g;n:30b5c2ed5572)) and I don't think the same result can be achieved without. 

What I find more important is where and how the MACs can be resolved to a node(id). In HopGlass the server replaces the MAC with the nodeid if it can find a node with that MAC. Meshviewer already had something built-in to get the actual node object from the node id in the gateway attribute IIRC. 
Should everything be done on the client to ensure most compatibility or on the server because of other reasons?
